### ISSUE TITLE
[Frontend] [Issue] Search Board of Director

### ISSUE THREAD

**Issue by camayacoast** [camaya-softdev/hoa-portal-front#10]
**Context of the Problem:**
 No data shown when searching board of director

**Proposed Solution:**
 Must show accurate data when searching board of director by name or contact number

**Screenshots:**
 
**Related Files:**
https://contextus.sharepoint.com/:x:/s/ITSoftwareDevelopment/EeFnyM3Zr5hIn5k-U1kkWN4BY-yELBIjO4LQGHuAZ4oNsg?e=8ACEFI

**Comment by rouelcalzita** [comment]
Search board of director **- Failed**

![Image](https://github.com/camaya-softdev/hoa-portal-front/assets/150649513/b83767dd-ee67-4e02-b706-8792b4beb363)

**Comment by MManuelCamaya** [comment]
Upon checking it is working also some issue of it not working was due to double space on the name so if you copy paste it wont display anything

tingin nalang po siguro pano natest at hindi gumana kasi sakin po working

![Image](https://github.com/camaya-softdev/hoa-portal-front/assets/144507982/65ce577c-8f3a-42eb-a68e-70eb2944e99b)

**Comment by cctc-rouelcalzita** [comment]
### QA Approved!
**Test Environment: Production**
Search board of director **- Passed**
